/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 50431
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPersona = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JL_APerFondo = new javax.swing.JLabel();
        ListPersona = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddPais = new javax.swing.JDialog();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ListPais = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        JMB_Frame = new javax.swing.JMenuBar();
        JM_Personas = new javax.swing.JMenu();
        JM_PersonasAdd = new javax.swing.JMenuItem();
        JM_PersonasList = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JM_Paises = new javax.swing.JMenu();
        JM_PaisesAdd = new javax.swing.JMenuItem();
        JM_PaisesList = new javax.swing.JMenuItem();

        AddPersona.setUndecorated(true);
        AddPersona.setResizable(false);
        AddPersona.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AddPersona.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 120, 60));

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel8.setText("Persona");
        AddPersona.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 220, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel1.setText("Nombre");
        AddPersona.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 290));

        JL_APerFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        AddPersona.getContentPane().add(JL_APerFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        ListPersona.setUndecorated(true);
        ListPersona.setResizable(false);
        ListPersona.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ListPersona.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 120, 60));

        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel9.setText("Persona");
        ListPersona.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 220, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel7.setText("Nombre");
        ListPersona.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        ListPersona.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        AddPais.setUndecorated(true);
        AddPais.setResizable(false);
        AddPais.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        AddPais.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 120, 60));

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel10.setText("Paises");
        AddPais.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 220, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel11.setText("Nombre");
        AddPais.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 290));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        AddPais.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        ListPais.setUndecorated(true);
        ListPais.setResizable(false);
        ListPais.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        ListPais.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 120, 60));

        jLabel12.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel12.setText("Paises");
        ListPais.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 220, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel13.setText("Nombre");
        ListPais.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 290));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        ListPais.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(153, 153, 153));
        Titulo.setText(" Control de los Casos de Coronavirus");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 650, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 290, 290));

        Fondo.setBackground(new java.awt.Color(0, 102, 204));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 580));

        JMB_Frame.setBorder(null);

        JM_Personas.setText("Personas");

        JM_PersonasAdd.setText("Agregar");
        JM_Personas.add(JM_PersonasAdd);

        JM_PersonasList.setText("Archivo");
        JM_Personas.add(JM_PersonasList);
        JM_Personas.add(jSeparator1);

        JMB_Frame.add(JM_Personas);

        JM_Paises.setText("Paises");

        JM_PaisesAdd.setText("Agregar");
        JM_Paises.add(JM_PaisesAdd);

        JM_PaisesList.setText("Archivo");
        JM_Paises.add(JM_PaisesList);

        JMB_Frame.add(JM_Paises);

        setJMenuBar(JMB_Frame);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AddPais;
    private javax.swing.JDialog AddPersona;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel JL_APerFondo;
    private javax.swing.JMenuBar JMB_Frame;
    private javax.swing.JMenu JM_Paises;
    private javax.swing.JMenuItem JM_PaisesAdd;
    private javax.swing.JMenuItem JM_PaisesList;
    private javax.swing.JMenu JM_Personas;
    private javax.swing.JMenuItem JM_PersonasAdd;
    private javax.swing.JMenuItem JM_PersonasList;
    private javax.swing.JDialog ListPais;
    private javax.swing.JDialog ListPersona;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
