
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 50431
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBG_Sexo = new javax.swing.ButtonGroup();
        JBG_Covid = new javax.swing.ButtonGroup();
        AddPersona = new javax.swing.JDialog();
        JT_PersonaNombre = new javax.swing.JTextField();
        JT_PersonaApellido = new javax.swing.JTextField();
        JT_PersonaNacionalidad = new javax.swing.JTextField();
        JFT_Edad = new javax.swing.JFormattedTextField();
        JChBo_Titulo = new java.awt.Checkbox();
        JCB_Vocacion = new javax.swing.JComboBox<>();
        JRB_Masculino = new javax.swing.JRadioButton();
        JRB_Femenino = new javax.swing.JRadioButton();
        JRB_Positivo = new javax.swing.JRadioButton();
        JRB_Negativo = new javax.swing.JRadioButton();
        JB_AddPersona = new javax.swing.JButton();
        JB_Home1 = new javax.swing.JButton();
        JB_Exit1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JL_APerFondo = new javax.swing.JLabel();
        JMB_Frame2 = new javax.swing.JMenuBar();
        JM_Personas2 = new javax.swing.JMenu();
        JM_PersonasList2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        JM_Paises2 = new javax.swing.JMenu();
        JM_PaisesAdd2 = new javax.swing.JMenuItem();
        JM_PaisesList2 = new javax.swing.JMenuItem();
        ListPersona = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPan_Mujeres = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JList_Mujeres = new javax.swing.JList<>();
        JPan_Hombres = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JList_Hombres = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        JList_Paises = new javax.swing.JList<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        JPan_Todas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree_Pais = new javax.swing.JTree();
        JPan_Positivas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTree_Positivas = new javax.swing.JTree();
        JB_Home2 = new javax.swing.JButton();
        JB_Exit2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JMB_Frame3 = new javax.swing.JMenuBar();
        JM_Personas3 = new javax.swing.JMenu();
        JM_PersonasAdd3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        JM_Paises3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        AddPais = new javax.swing.JDialog();
        JDC_Fecha = new com.toedter.calendar.JDateChooser();
        JT_PaisesName = new javax.swing.JTextField();
        JT_himno = new javax.swing.JTextField();
        JB_Color = new javax.swing.JButton();
        JB_AddPaises = new javax.swing.JButton();
        JB_Exit = new javax.swing.JButton();
        JB_Home = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JMB_Frame1 = new javax.swing.JMenuBar();
        JM_Personas1 = new javax.swing.JMenu();
        JM_PersonasAdd1 = new javax.swing.JMenuItem();
        JM_PersonasList1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        JM_Paises1 = new javax.swing.JMenu();
        JM_PaisesList1 = new javax.swing.JMenuItem();
        JPUM_Paises = new javax.swing.JPopupMenu();
        JMRC_Paises = new javax.swing.JMenu();
        JM_ModPai = new javax.swing.JMenuItem();
        JM_DelPai = new javax.swing.JMenuItem();
        JPUM_Personas = new javax.swing.JPopupMenu();
        JMRC_Personas1 = new javax.swing.JMenu();
        JM_AddPer = new javax.swing.JMenuItem();
        JM_ModPer = new javax.swing.JMenuItem();
        JM_DelPer = new javax.swing.JMenuItem();
        Titulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        JMB_Frame = new javax.swing.JMenuBar();
        JM_Personas = new javax.swing.JMenu();
        JM_PersonasAdd = new javax.swing.JMenuItem();
        JM_PersonasList = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JM_Paises = new javax.swing.JMenu();
        JM_PaisesAdd = new javax.swing.JMenuItem();
        JM_PaisesList = new javax.swing.JMenuItem();

        AddPersona.setUndecorated(true);
        AddPersona.setResizable(false);
        AddPersona.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        AddPersona.getContentPane().add(JT_PersonaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, -1));
        AddPersona.getContentPane().add(JT_PersonaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, -1));
        AddPersona.getContentPane().add(JT_PersonaNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 90, -1));

        try {
            JFT_Edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        AddPersona.getContentPane().add(JFT_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 30, -1));
        AddPersona.getContentPane().add(JChBo_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        JCB_Vocacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnico", "Agricultor", "Oficinista" }));
        JCB_Vocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_VocacionActionPerformed(evt);
            }
        });
        AddPersona.getContentPane().add(JCB_Vocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        JBG_Sexo.add(JRB_Masculino);
        JRB_Masculino.setText("Masculino");
        AddPersona.getContentPane().add(JRB_Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        JBG_Sexo.add(JRB_Femenino);
        JRB_Femenino.setText("Femenino");
        AddPersona.getContentPane().add(JRB_Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        JBG_Covid.add(JRB_Positivo);
        JRB_Positivo.setText("Positivo");
        AddPersona.getContentPane().add(JRB_Positivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        JBG_Covid.add(JRB_Negativo);
        JRB_Negativo.setText("Negativo");
        AddPersona.getContentPane().add(JRB_Negativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        JB_AddPersona.setText("Agregar");
        JB_AddPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddPersonaActionPerformed(evt);
            }
        });
        AddPersona.getContentPane().add(JB_AddPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 100, 50));

        JB_Home1.setText("Home");
        JB_Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Home1ActionPerformed(evt);
            }
        });
        AddPersona.getContentPane().add(JB_Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 40));

        JB_Exit1.setText("X");
        JB_Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Exit1ActionPerformed(evt);
            }
        });
        AddPersona.getContentPane().add(JB_Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, 40));

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel8.setText("Persona");
        AddPersona.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 220, 80));

        jLabel6.setText("Nombre");
        AddPersona.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel14.setText("Nacionalidad");
        AddPersona.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel15.setText("Edad");
        AddPersona.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel16.setText("Sexo");
        AddPersona.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel17.setText("Vocacion");
        AddPersona.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel18.setText("Titulo");
        AddPersona.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, 20));

        jLabel19.setText("Covid-19");
        AddPersona.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        jLabel25.setText("Universitario");
        AddPersona.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        jLabel27.setText("Apellido");
        AddPersona.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel1.setText("Nombre");
        AddPersona.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 290));

        JL_APerFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        AddPersona.getContentPane().add(JL_APerFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        JMB_Frame2.setBorder(null);

        JM_Personas2.setText("Personas");

        JM_PersonasList2.setText("Archivo");
        JM_PersonasList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PersonasList2ActionPerformed(evt);
            }
        });
        JM_Personas2.add(JM_PersonasList2);
        JM_Personas2.add(jSeparator3);

        JMB_Frame2.add(JM_Personas2);

        JM_Paises2.setText("Paises");

        JM_PaisesAdd2.setText("Agregar");
        JM_PaisesAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PaisesAdd2ActionPerformed(evt);
            }
        });
        JM_Paises2.add(JM_PaisesAdd2);

        JM_PaisesList2.setText("Archivo");
        JM_PaisesList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PaisesList2ActionPerformed(evt);
            }
        });
        JM_Paises2.add(JM_PaisesList2);

        JMB_Frame2.add(JM_Paises2);

        AddPersona.setJMenuBar(JMB_Frame2);

        ListPersona.setUndecorated(true);
        ListPersona.setResizable(false);
        ListPersona.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setPreferredSize(new java.awt.Dimension(640, 130));

        JList_Mujeres.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(JList_Mujeres);

        javax.swing.GroupLayout JPan_MujeresLayout = new javax.swing.GroupLayout(JPan_Mujeres);
        JPan_Mujeres.setLayout(JPan_MujeresLayout);
        JPan_MujeresLayout.setHorizontalGroup(
            JPan_MujeresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPan_MujeresLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        JPan_MujeresLayout.setVerticalGroup(
            JPan_MujeresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPan_MujeresLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mujeres", JPan_Mujeres);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(640, 130));

        JList_Hombres.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(JList_Hombres);

        javax.swing.GroupLayout JPan_HombresLayout = new javax.swing.GroupLayout(JPan_Hombres);
        JPan_Hombres.setLayout(JPan_HombresLayout);
        JPan_HombresLayout.setHorizontalGroup(
            JPan_HombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPan_HombresLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        JPan_HombresLayout.setVerticalGroup(
            JPan_HombresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPan_HombresLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hombres", JPan_Hombres);

        JList_Paises.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(JList_Paises);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Paises", jPanel1);

        ListPersona.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 360, 210));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        JTree_Pais.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree_Pais.setPreferredSize(new java.awt.Dimension(350, 150));
        JTree_Pais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTree_PaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTree_Pais);

        JPan_Todas.add(jScrollPane1);

        jTabbedPane2.addTab("Paises", JPan_Todas);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Pasies");
        JTree_Positivas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree_Positivas.setPreferredSize(new java.awt.Dimension(350, 150));
        jScrollPane3.setViewportView(JTree_Positivas);

        JPan_Positivas.add(jScrollPane3);

        jTabbedPane2.addTab("Positivas", JPan_Positivas);

        ListPersona.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 360, 240));

        JB_Home2.setText("Home");
        JB_Home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Home2ActionPerformed(evt);
            }
        });
        ListPersona.getContentPane().add(JB_Home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        JB_Exit2.setText("X");
        JB_Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Exit2ActionPerformed(evt);
            }
        });
        ListPersona.getContentPane().add(JB_Exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, 40));

        jButton1.setText("Exportar Positivos");
        ListPersona.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 200, -1));

        jButton2.setText("Agregar Pais en Arbol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ListPersona.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 200, -1));

        jLabel26.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel26.setText("Archivos");
        ListPersona.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 240, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel7.setText("Nombre");
        ListPersona.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        ListPersona.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        JMB_Frame3.setBorder(null);

        JM_Personas3.setText("Personas");
        JM_Personas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_Personas3ActionPerformed(evt);
            }
        });

        JM_PersonasAdd3.setText("Agregar");
        JM_PersonasAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PersonasAdd3ActionPerformed(evt);
            }
        });
        JM_Personas3.add(JM_PersonasAdd3);
        JM_Personas3.add(jSeparator4);

        JMB_Frame3.add(JM_Personas3);

        JM_Paises3.setText("Paises");

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JM_Paises3.add(jMenuItem1);

        JMB_Frame3.add(JM_Paises3);

        ListPersona.setJMenuBar(JMB_Frame3);

        AddPais.setUndecorated(true);
        AddPais.setResizable(false);
        AddPais.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        AddPais.getContentPane().add(JDC_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 150, -1));
        AddPais.getContentPane().add(JT_PaisesName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, -1));
        AddPais.getContentPane().add(JT_himno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 90, -1));

        JB_Color.setText("Color");
        JB_Color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ColorMouseClicked(evt);
            }
        });
        AddPais.getContentPane().add(JB_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 90, 30));

        JB_AddPaises.setText("Agregar");
        JB_AddPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddPaisesActionPerformed(evt);
            }
        });
        AddPais.getContentPane().add(JB_AddPaises, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 120, 60));

        JB_Exit.setText("X");
        JB_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ExitActionPerformed(evt);
            }
        });
        AddPais.getContentPane().add(JB_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, 40));

        JB_Home.setText("Home");
        JB_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_HomeActionPerformed(evt);
            }
        });
        AddPais.getContentPane().add(JB_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        jLabel21.setText("Himno Nacional");
        AddPais.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel22.setText("Nombre");
        AddPais.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel23.setText("Color de bandera");
        AddPais.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel24.setText("Fecha de fundación");
        AddPais.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        jLabel10.setText("Paises");
        AddPais.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 220, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel11.setText("Nombre");
        AddPais.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, 290));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        AddPais.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        JMB_Frame1.setBorder(null);

        JM_Personas1.setText("Personas");

        JM_PersonasAdd1.setText("Agregar");
        JM_PersonasAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PersonasAdd1ActionPerformed(evt);
            }
        });
        JM_Personas1.add(JM_PersonasAdd1);

        JM_PersonasList1.setText("Archivo");
        JM_PersonasList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PersonasList1ActionPerformed(evt);
            }
        });
        JM_Personas1.add(JM_PersonasList1);
        JM_Personas1.add(jSeparator2);

        JMB_Frame1.add(JM_Personas1);

        JM_Paises1.setText("Paises");

        JM_PaisesList1.setText("Archivo");
        JM_PaisesList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PaisesList1ActionPerformed(evt);
            }
        });
        JM_Paises1.add(JM_PaisesList1);

        JMB_Frame1.add(JM_Paises1);

        AddPais.setJMenuBar(JMB_Frame1);

        JMRC_Paises.setText("Paises\n");
        JMRC_Paises.setActionCommand("Paises");

        JM_ModPai.setText("Modificar");
        JM_ModPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_ModPaiActionPerformed(evt);
            }
        });
        JMRC_Paises.add(JM_ModPai);

        JM_DelPai.setText("Eliminar");
        JM_DelPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_DelPaiActionPerformed(evt);
            }
        });
        JMRC_Paises.add(JM_DelPai);

        JPUM_Paises.add(JMRC_Paises);

        JMRC_Personas1.setText("jMenu1");

        JM_AddPer.setText("jMenuItem2");
        JM_AddPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_AddPerActionPerformed(evt);
            }
        });
        JMRC_Personas1.add(JM_AddPer);

        JM_ModPer.setText("jMenuItem2");
        JM_ModPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_ModPerActionPerformed(evt);
            }
        });
        JMRC_Personas1.add(JM_ModPer);

        JM_DelPer.setText("jMenuItem2");
        JM_DelPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_DelPerActionPerformed(evt);
            }
        });
        JMRC_Personas1.add(JM_DelPer);

        JPUM_Personas.add(JMRC_Personas1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(153, 153, 153));
        Titulo.setText(" Control de los Casos de Coronavirus");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 650, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UN_emblem_gold.svg.png"))); // NOI18N
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 290, 290));

        Fondo.setBackground(new java.awt.Color(0, 102, 204));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f73ef9ec5882eab32771edb39399765f.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 580));

        JMB_Frame.setBorder(null);

        JM_Personas.setText("Personas");
        JM_Personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PersonasActionPerformed(evt);
            }
        });

        JM_PersonasAdd.setText("Agregar");
        JM_PersonasAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PersonasAddActionPerformed(evt);
            }
        });
        JM_Personas.add(JM_PersonasAdd);

        JM_PersonasList.setText("Archivo");
        JM_PersonasList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PersonasListActionPerformed(evt);
            }
        });
        JM_Personas.add(JM_PersonasList);
        JM_Personas.add(jSeparator1);

        JMB_Frame.add(JM_Personas);

        JM_Paises.setText("Paises");

        JM_PaisesAdd.setText("Agregar");
        JM_PaisesAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PaisesAddActionPerformed(evt);
            }
        });
        JM_Paises.add(JM_PaisesAdd);

        JM_PaisesList.setText("Archivo");
        JM_PaisesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PaisesListActionPerformed(evt);
            }
        });
        JM_Paises.add(JM_PaisesList);

        JMB_Frame.add(JM_Paises);

        setJMenuBar(JMB_Frame);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCB_VocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_VocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCB_VocacionActionPerformed

    private void JB_ColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ColorMouseClicked
        JB_Color.setForeground(JColorChooser.showDialog(this, "Elija el Color De la bandera", Color.WHITE));
    }//GEN-LAST:event_JB_ColorMouseClicked

    private void JM_PersonasAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PersonasAddActionPerformed
        AddPersona.setVisible(true);
        AddPersona.pack();
        AddPersona.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_JM_PersonasAddActionPerformed

    private void JM_PersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PersonasActionPerformed
        ListPersona.setVisible(true);
        ListPersona.pack();
        ListPersona.setLocationRelativeTo(this);
        this.setVisible(false);    }//GEN-LAST:event_JM_PersonasActionPerformed

    private void JM_PaisesAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PaisesAddActionPerformed
        AddPais.setVisible(true);
        AddPais.pack();
        AddPais.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_JM_PaisesAddActionPerformed

    private void JM_PaisesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PaisesListActionPerformed
        ListPersona.setVisible(true);
        ListPersona.pack();
        ListPersona.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_JM_PaisesListActionPerformed

    private void JB_Home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Home1ActionPerformed
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        AddPersona.setVisible(false);
    }//GEN-LAST:event_JB_Home1ActionPerformed

    private void JB_Home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Home2ActionPerformed
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        ListPersona.setVisible(false);
    }//GEN-LAST:event_JB_Home2ActionPerformed

    private void JB_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_HomeActionPerformed
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        AddPais.setVisible(false);
    }//GEN-LAST:event_JB_HomeActionPerformed

    private void JM_PersonasListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PersonasListActionPerformed
        ListPersona.setVisible(true);
        ListPersona.pack();
        ListPersona.setLocationRelativeTo(this);
        this.setVisible(false);
    }//GEN-LAST:event_JM_PersonasListActionPerformed

    private void JB_Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Exit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_Exit1ActionPerformed

    private void JB_Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Exit2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_Exit2ActionPerformed

    private void JB_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_ExitActionPerformed

    private boolean Contagio() {
        boolean ret = false;
        if (JRB_Positivo.isSelected()) {
            ret = true;
        }
        return ret;
    }

    private boolean ContagioMod() {
        boolean ret = false;
        if (JRB_Positivo.isSelected()) {
            ret = true;
        }
        return ret;
    }

    private boolean Titulo() {
        boolean ret = false;
        if (JChBo_Titulo.isEnabled()) {
            ret = true;
        }
        return ret;
    }

    private String sexo() {
        String ret = null;
        if (JRB_Femenino.isSelected()) {
            ret = "Femenino";
        } else if (JRB_Masculino.isSelected()) {
            ret = "Masculino";
        }
        return ret;
    }

    private void ResetPersona() {
        this.JT_PersonaNacionalidad.setText("");
        this.JT_PersonaNombre.setText("");
        this.JT_PersonaApellido.setText("");
        this.JRB_Femenino.setSelected(false);
        this.JRB_Masculino.setSelected(false);
        this.JRB_Positivo.setSelected(false);
        this.JRB_Negativo.setSelected(false);
        this.JChBo_Titulo.setState(false);
        this.JCB_Vocacion.setSelectedIndex(0);
        this.JFT_Edad.setText("");
    }

    private void JB_AddPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddPersonaActionPerformed
        DefaultListModel ListModelMujeres = (DefaultListModel) JList_Mujeres.getModel();
        DefaultListModel ListModelHombres = (DefaultListModel) JList_Hombres.getModel();
        try {
            if (JRB_Femenino.isSelected()) {
                ListModelMujeres.addElement(new Persona(JT_PersonaNacionalidad.getText(), JT_PersonaNombre.getText(), JT_PersonaApellido.getText(), sexo(), JCB_Vocacion.getSelectedItem().toString(), Titulo(), Integer.parseInt(JFT_Edad.getText()), Contagio()));
            } else if (JRB_Masculino.isSelected()) {
                ListModelHombres.addElement(new Persona(JT_PersonaNacionalidad.getText(), JT_PersonaNombre.getText(), JT_PersonaApellido.getText(), sexo(), JCB_Vocacion.getSelectedItem().toString(), Titulo(), Integer.parseInt(JFT_Edad.getText()), Contagio()));
            }
            JOptionPane.showMessageDialog(this, "Agregado exitosamente.");
            ResetPersona();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_JB_AddPersonaActionPerformed

    private void ResetPais() {
        this.JT_PaisesName.setText("");
        this.JT_himno.setText("");
        this.JB_Color.setForeground(Color.WHITE);
        this.JDC_Fecha.setDateFormatString("");
    }

    private void JB_AddPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddPaisesActionPerformed
        DefaultListModel ListModelPais = (DefaultListModel) JList_Paises.getModel();
        try {
            ListModelPais.addElement(new Pais(JT_PaisesName.getText(), JT_himno.getText(), JDC_Fecha.getDate(), JB_Color.getForeground()));
            JOptionPane.showMessageDialog(this, "Agregado exitosamente.");
            ResetPais();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_JB_AddPaisesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JList_Mujeres.getSelectedIndex() < 0 && JList_Hombres.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "No hay nadie seleccionado.");
        } else if (JList_Hombres.getSelectedIndex() >= 0 && JList_Hombres.getSelectedIndex() >= 0) {
            JOptionPane.showMessageDialog(this, "Seleccione Solo una Persona.");
        } else if (JList_Paises.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un Pais");
        } else if (JList_Mujeres.getSelectedIndex() >= 0 && JList_Paises.getSelectedIndex() >= 0) {
            DefaultTreeModel TreeModel_Pais = (DefaultTreeModel) JTree_Pais.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) TreeModel_Pais.getRoot();
            DefaultListModel modeloLISTA1 = (DefaultListModel) JList_Paises.getModel();
            String Pais;
            Pais = ((Pais) modeloLISTA1.get(JList_Paises.getSelectedIndex())).getNombre();
            DefaultListModel modeloLISTA = (DefaultListModel) JList_Mujeres.getModel();
            String Nombre, Sexo;
            Sexo = "Femenino";
            Nombre = ((Persona) modeloLISTA.get(JList_Mujeres.getSelectedIndex())).getNombre();
            boolean flag = true;
            for (int i = 0; i < root.getChildCount(); i++) {
                if (root.getChildAt(i).toString().equals(Pais)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(Nombre);
                    ((DefaultMutableTreeNode) root.getChildAt(i)).add(p);
                    JOptionPane.showMessageDialog(this, "Nodo ya Creado");
                }
                flag = false;
            }
            if (flag == true) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(Pais);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(Nombre);
                DefaultMutableTreeNode s = new DefaultMutableTreeNode(Sexo);
                s.add(p);
                n.add(s);
                root.add(n);
                JOptionPane.showMessageDialog(this, "Nuevo Nodo Creado");
            }
            TreeModel_Pais.reload();
            JOptionPane.showMessageDialog(this, "Mujer creada en el arbol");
        } else if (JList_Hombres.getSelectedIndex() >= 0 && JList_Paises.getSelectedIndex() >= 0) {
            DefaultTreeModel TreeModel_Pais = (DefaultTreeModel) JTree_Pais.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) TreeModel_Pais.getRoot();
            DefaultListModel modeloLISTA1 = (DefaultListModel) JList_Paises.getModel();
            String Pais;
            Pais = ((Persona) modeloLISTA1.get(JList_Paises.getSelectedIndex())).getNombre();
            DefaultListModel modeloLISTA = (DefaultListModel) JList_Hombres.getModel();
            String Nombre, Sexo;
            Nombre = ((Persona) modeloLISTA.get(JList_Hombres.getSelectedIndex())).getNombre();
            Sexo = "Femenino";
            boolean flag = true;
            for (int i = 0; i < root.getChildCount(); i++) {
                if (root.getChildAt(i).toString().equals(Pais)) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(Nombre);
                    ((DefaultMutableTreeNode) root.getChildAt(i)).add(p);
                    flag = false;
                    JOptionPane.showMessageDialog(this, "Nodo ya Creado");
                }
            }
            if (flag == true) {
                DefaultMutableTreeNode n = new DefaultMutableTreeNode(Pais);
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(Nombre);
                DefaultMutableTreeNode s = new DefaultMutableTreeNode(Sexo);
                s.add(p);
                n.add(s);
                root.add(n);
                JOptionPane.showMessageDialog(this, "Nuevo Nodo Creado");
            }
            TreeModel_Pais.reload();
            JOptionPane.showMessageDialog(this, "Hombre creado en el arbol");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JM_PersonasAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PersonasAdd1ActionPerformed
        AddPersona.setVisible(true);
        AddPersona.pack();
        AddPersona.setLocationRelativeTo(this);
        AddPais.setVisible(false);

    }//GEN-LAST:event_JM_PersonasAdd1ActionPerformed

    private void JM_PersonasList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PersonasList1ActionPerformed
        ListPersona.setVisible(true);
        ListPersona.pack();
        ListPersona.setLocationRelativeTo(this);
        AddPais.setVisible(false);

    }//GEN-LAST:event_JM_PersonasList1ActionPerformed

    private void JM_PaisesList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PaisesList1ActionPerformed
        ListPersona.setVisible(true);
        ListPersona.pack();
        ListPersona.setLocationRelativeTo(this);
        AddPais.setVisible(false);
    }//GEN-LAST:event_JM_PaisesList1ActionPerformed

    private void JM_PersonasList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PersonasList2ActionPerformed
        ListPersona.setVisible(true);
        ListPersona.pack();
        ListPersona.setLocationRelativeTo(this);
        AddPersona.setVisible(false);

    }//GEN-LAST:event_JM_PersonasList2ActionPerformed

    private void JM_PaisesAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PaisesAdd2ActionPerformed
        AddPais.setVisible(true);
        AddPais.pack();
        AddPais.setLocationRelativeTo(this);
        AddPersona.setVisible(false);
    }//GEN-LAST:event_JM_PaisesAdd2ActionPerformed

    private void JM_PaisesList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PaisesList2ActionPerformed
        ListPersona.setVisible(true);
        ListPersona.pack();
        ListPersona.setLocationRelativeTo(this);
        AddPersona.setVisible(false);
    }//GEN-LAST:event_JM_PaisesList2ActionPerformed

    private void JM_PersonasAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PersonasAdd3ActionPerformed
        AddPersona.setVisible(true);
        AddPersona.pack();
        AddPersona.setLocationRelativeTo(this);
        ListPersona.setVisible(false);

    }//GEN-LAST:event_JM_PersonasAdd3ActionPerformed

    private void JM_Personas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_Personas3ActionPerformed

    }//GEN-LAST:event_JM_Personas3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListPersona.setVisible(false);
        AddPais.setLocationRelativeTo(this);
        AddPais.setVisible(true);
        AddPais.pack();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JM_AddPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_AddPerActionPerformed
        AddPersona.setVisible(true);
        AddPersona.pack();
        AddPersona.setLocationRelativeTo(null);
        ListPersona.setVisible(false);
    }//GEN-LAST:event_JM_AddPerActionPerformed

    private void JTree_PaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTree_PaisMouseClicked
        if (evt.isMetaDown()) {
            int row = JTree_Pais.getClosestRowForLocation(evt.getX(), evt.getY());
            JTree_Pais.setSelectionRow(row);
            Object v1 = JTree_Pais.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;

            if (nodo_seleccionado.getUserObject() instanceof Pais) {
                pais_seleccionado = (Pais) nodo_seleccionado.getUserObject();
                JPUM_Paises.show(evt.getComponent(), evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getUserObject() instanceof Persona) {
                persona_seleccionada = (Persona) nodo_seleccionado.getUserObject();
                JPUM_Personas.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_JTree_PaisMouseClicked

    private void JM_ModPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_ModPaiActionPerformed
        pais_seleccionado.setBandera(JColorChooser.showDialog(this, "Nuevo Color", Color.BLACK));
        pais_seleccionado.setNombre(JOptionPane.showInputDialog(this, "Nombre"));
    }//GEN-LAST:event_JM_ModPaiActionPerformed

    private void JM_ModPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_ModPerActionPerformed
        persona_seleccionada.setNombre(JOptionPane.showInputDialog(this, "Nombre:"));
        persona_seleccionada.setApellido(JOptionPane.showInputDialog(this, "Apellido:"));
        persona_seleccionada.setNacionalidad(JOptionPane.showInputDialog(this, "Nacionalidad:"));
        persona_seleccionada.setEdad(Integer.parseInt(JOptionPane.showInputDialog(this, "Edad:")));
    }//GEN-LAST:event_JM_ModPerActionPerformed

    private void JM_DelPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_DelPaiActionPerformed
        try {
            int response = JOptionPane.showConfirmDialog(this, "Seguro de Eliminar?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                DefaultTreeModel m = (DefaultTreeModel) JTree_Pais.getModel();
                m.removeNodeFromParent(nodo_seleccionado);
                m.reload();
            }
        } catch (Exception e) {
            System.out.println("Error.");
        }

    }//GEN-LAST:event_JM_DelPaiActionPerformed

    private void JM_DelPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_DelPerActionPerformed
        try {
            DefaultTreeModel m = (DefaultTreeModel) JTree_Pais.getModel();
            m.removeNodeFromParent((MutableTreeNode) persona_seleccionada);
            m.reload();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error.");
        }
    }//GEN-LAST:event_JM_DelPerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AddPais;
    private javax.swing.JDialog AddPersona;
    private javax.swing.JLabel Fondo;
    private javax.swing.ButtonGroup JBG_Covid;
    private javax.swing.ButtonGroup JBG_Sexo;
    private javax.swing.JButton JB_AddPaises;
    private javax.swing.JButton JB_AddPersona;
    private javax.swing.JButton JB_Color;
    private javax.swing.JButton JB_Exit;
    private javax.swing.JButton JB_Exit1;
    private javax.swing.JButton JB_Exit2;
    private javax.swing.JButton JB_Home;
    private javax.swing.JButton JB_Home1;
    private javax.swing.JButton JB_Home2;
    private javax.swing.JComboBox<String> JCB_Vocacion;
    private java.awt.Checkbox JChBo_Titulo;
    private com.toedter.calendar.JDateChooser JDC_Fecha;
    private javax.swing.JFormattedTextField JFT_Edad;
    private javax.swing.JLabel JL_APerFondo;
    private javax.swing.JList<String> JList_Hombres;
    private javax.swing.JList<String> JList_Mujeres;
    private javax.swing.JList<String> JList_Paises;
    private javax.swing.JMenuBar JMB_Frame;
    private javax.swing.JMenuBar JMB_Frame1;
    private javax.swing.JMenuBar JMB_Frame2;
    private javax.swing.JMenuBar JMB_Frame3;
    private javax.swing.JMenu JMRC_Paises;
    private javax.swing.JMenu JMRC_Personas1;
    private javax.swing.JMenuItem JM_AddPer;
    private javax.swing.JMenuItem JM_DelPai;
    private javax.swing.JMenuItem JM_DelPer;
    private javax.swing.JMenuItem JM_ModPai;
    private javax.swing.JMenuItem JM_ModPer;
    private javax.swing.JMenu JM_Paises;
    private javax.swing.JMenu JM_Paises1;
    private javax.swing.JMenu JM_Paises2;
    private javax.swing.JMenu JM_Paises3;
    private javax.swing.JMenuItem JM_PaisesAdd;
    private javax.swing.JMenuItem JM_PaisesAdd2;
    private javax.swing.JMenuItem JM_PaisesList;
    private javax.swing.JMenuItem JM_PaisesList1;
    private javax.swing.JMenuItem JM_PaisesList2;
    private javax.swing.JMenu JM_Personas;
    private javax.swing.JMenu JM_Personas1;
    private javax.swing.JMenu JM_Personas2;
    private javax.swing.JMenu JM_Personas3;
    private javax.swing.JMenuItem JM_PersonasAdd;
    private javax.swing.JMenuItem JM_PersonasAdd1;
    private javax.swing.JMenuItem JM_PersonasAdd3;
    private javax.swing.JMenuItem JM_PersonasList;
    private javax.swing.JMenuItem JM_PersonasList1;
    private javax.swing.JMenuItem JM_PersonasList2;
    private javax.swing.JPopupMenu JPUM_Paises;
    private javax.swing.JPopupMenu JPUM_Personas;
    private javax.swing.JPanel JPan_Hombres;
    private javax.swing.JPanel JPan_Mujeres;
    private javax.swing.JPanel JPan_Positivas;
    private javax.swing.JPanel JPan_Todas;
    private javax.swing.JRadioButton JRB_Femenino;
    private javax.swing.JRadioButton JRB_Masculino;
    private javax.swing.JRadioButton JRB_Negativo;
    private javax.swing.JRadioButton JRB_Positivo;
    private javax.swing.JTextField JT_PaisesName;
    private javax.swing.JTextField JT_PersonaApellido;
    private javax.swing.JTextField JT_PersonaNacionalidad;
    private javax.swing.JTextField JT_PersonaNombre;
    private javax.swing.JTextField JT_himno;
    private javax.swing.JTree JTree_Pais;
    private javax.swing.JTree JTree_Positivas;
    private javax.swing.JDialog ListPersona;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
    DefaultMutableTreeNode nodo_seleccionado;
    Persona persona_seleccionada;
    Pais pais_seleccionado;
}
